fix(modem_info): exclude zbus info from bearer report
omnect/omnect-device-service pull request #104
Opened 2024-08-20 08:44 UTC by empwilli

2024-08-20 09:50 UTC, mlilien approved these changes

2024-08-20 10:54 UTC, mlilien requested changes

2024-08-20 10:54 UTC, mlilien commented on Cargo.toml
> +version = "0.22.2"
that should be a 0.22.3. please get the latest changes from main.

2024-08-20 11:36 UTC, mlilien approved these changes

2024-09-12 18:32 UTC, JanZachmann requested changes

2024-10-31 09:45 UTC, closed without merging